# Generated by Django 3.2.13 on 2022-05-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SHACLPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('shacl_pattern', models.TextField(default='')),
                ('description', models.TextField()),
                ('pattern_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern.classpattern')),
            ],
        ),
    ]
